# Generated by Django 3.1.2 on 2020-11-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
