# Generated by Django 3.1.2 on 2020-12-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
